{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "influx-gateway.fullname" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "influx-gateway.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: http
      path: /healthz
      interval: 30s
{{- end }}
